### ISSUE TITLE
"Rust" biome missing on Superstorm Expanse (and maybe Desolate and Ferocious planets too)

### ISSUE THREAD

**Issue by evonzee** [sleepySva/sva_arcana#12]
I'm doing my first Arcana run on a fairly heavily modded server, and I'm finding it impossible to land on (most? all?) Superstorm Expanse planets.  The error in the server log says:

[Error] UniverseServer: error during world create: (BiomeException) Failed to parse biome: 'rust'

I looked through the various mods I'm using and found that Betabound has both a patch for a "rust" biome as well as a new sb_rust biome definition.  I also found that FU refers to a "rust" biome, but calls it a "secondaryRegion" rather than a "subRegion".  

I'm not super familiar with the nuances of starbound modding, but it seems like this is an incompatibility issue with one of those two other mods - though I sure can't see why based on my limited understanding.   Has anyone else experienced this issue?

If relevant (and if you're willing to look) my mod list is [here](https://github.com/evonzee/starbound-modpack-launcher/wiki).

Thanks!

**Comment by sleepySva** [comment]
Apologies for the late reply, this issue should be fixed in the next patch since that biome won't appear anymore in Superstorm Expanse planets

(Not sure what was the issue though, I think rust was a vanilla subbiome which shouldn't have compatibility issues, but one of those mods could've changed it a bit. I haven't used FU in a while so I'm unfamiliar with its changes)
